baseURL = 'https://valinsky.dev/'
languageCode = 'en-us'
title = "Valinsky"
theme = 'holy'
DefaultContentLanguage = "en"
# enableInlineShortcodes = true

[params]
  copyright = "© Valinsky"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
